stages:
  - deploy

deploy_prod:
  stage: deploy
  tags:
    - appointment
  script:
    - mvn clean
    - mvn package
    - mv ./target/ws_parserpdf $CATALINA_HOME/webapps
  environment:
    name: production
  only:
  - master