stages:
  - deploy

deploy_prod:
  stage: deploy
  tags:
    - appointment
  script:
    - mvn clean
    - mvn org.apache.maven.plugins:maven-war-plugin:2.3:exploded
    - mv ./target/ws_parserpdf $CATALINA_HOME/webapps
  environment:
    name: production
  only:
  - master