stages:
  - deploy

deploy_prod:
  stage: deploy
  tags:
    - appointment
  script:
    - mvn clean
    - mvn compile
    - mvn org.apache.maven.plugins:maven-war-plugin:2.3:exploded
    - rsync  --archive ./target/poc/ $CATALINA_HOME/webapps/poc/
  environment:
    name: production
  only:
  - master